---
- name: Deploy Voting App
  hosts: localhost
  gather_facts: true
  become: true

  tasks:
    - name: Bootstrap Python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Clone GitHub repository
      git:
        repo: https://github.com/AB-Ynov/voting-app.git
        dest: /opt/voting-app

    - name: Install dependencies
      command: pip install -r /opt/voting-app/requirements.txt

    - name: Start SSH service in Docker container
      command: service ssh start
      ignore_errors: yes

    - name: Provisioning with Ansible
      ansible_connection: local
      tasks:
        - name: Execute Ansible playbook
          command: ansible-playbook -e packer_build_name="docker" -e packer_builder_type=docker -e ansible_ssh_private_key_file=/tmp/ansible-key86810211 -i /tmp/packer-provisioner-ansible2117713205 /opt/voting-app/deploy.yml
