version: '3'

services:
  web:
    image: abynov/voting-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mydatabasepassword
