- name: Provision Python
  hosts: all
  gather_facts: false
  tasks:
    - name: Boostrap python
      raw: test -e /usr/bin/python3 || (apt-get -y update && apt-get install -y python3 python3-pip python3-apt)

- hosts: default  
  gather_facts: true
  roles:
    - role: ./deps/
      vars:
        pip_packages: ["redis","flask","requests"]
  tasks:
    - name: "Copy source code to container"
      copy:
        src: "../azure-vote"
        dest: "/app"