name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Unit test
        run: |
          pip install -r requirements.txt
          pytest
