name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
          persist-credentials: false

      - name: Lint Python code
        run: |
          pip install flake8
          flake8 --statistics

      - name: Security check
        run: |
          pip install bandit
          bandit -r .

      - name: Install Packer plugins
        run: |
          packer plugins install github.com/hashicorp/ansible
          packer plugins install github.com/hashicorp/docker

      - name: Build Packer image
        run: packer build packer.json

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push abynov/voting-app:latest
