name: Tests 

on:
  workflow_dispatch:
  push:
    branches: 
        - J2

jobs:
  LintAndSec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Python Lint
      run: |
        pip install flake8
        flake8 azure-vote/main.py

    - name: Is secure ?
      run: |
        pip install safety
        safety check -r azure-vote/main.py
    
  BuildPacker:
    runs-on: ubuntu-latest
    needs: [LintAndSec]
    steps:
        
    - uses: actions/checkout@v3

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      with:
        version: "latest"

    - name: Run `packer init`
      id: init
      run: "packer init ./Packer/docker-voting-app.pkr.hcl"

    - name: Run `packer validate`
      id: validate
      run: "packer validate ./Packer/docker-voting-app.pkr.hcl"

    - name: Build Artifact
      run: packer build -color=false -on-error=abort ./Packer/docker-voting-app.pkr.hcl
    
  IntegrationTests:
    runs-on: ubuntu-latest
    needs: [LintAndSec, BuildPacker]
    steps:
      - uses: actions/checkout@v3
      - name: Launch compose file
        run: |
          docker-compose up -d
          if [[ $(curl -s -XGET http://localhost:8080/ | grep results | awk '{print $5}') -eq 0 ]]; then echo OK GET; else echo KO exit 255; fi
          if [[ $(curl -s -XPOST http://localhost:8080/ -d 'vote=Cats' | grep results | awk '{print $5}') -eq 1 ]]; then echo OK POST; else echo KO exit 255; fi
          docker-compose down